### PR TITLE
Update Tests - for 1.1

### PR DESCRIPTION
**Pull request by TomDonoghue**
This is a work in progress PR, partly related to #127 

Currently this just has a bunch of clean ups & orgs for testing. 

What I was originally looking into is potentially refactoring some of the tests, to be a little more dependent on checking properties of the signals, rather than shipping a bunch of data that is only used to check consistency. 

At the least, I think we can & should have a separate script that can be used to regenerate all the test data when we need it. 

Note: if there is more to do on this idea, we can add it in here, so this PR is not ready to merge yet.

### CODE REVIEW

**Comment by rdgao** [comment]
agreed - and yeah I think we can replace all the real data with simulated data, if for nothing else other than not shipping the real data

**Comment by rdgao** [comment]
do you want to task out some of this so I can help with it? on the project board 😮 ?

or we can meet at some point and figure out roughly what we want to do here

**Comment by rdgao** [comment]
the projects tab beside the PR tab up top? It's like a Trello style thing, pretty sure you told me about this

**Comment by TomDonoghue** [comment]
Okay - so I'm going call this one here on test updates that we can merge in for 1.1 - so this should be ready to merge, if it looks good. In the end it has relatively minor updates (doesn't include the test overhaul). 

I think the full update of the tests should wait for 2.0, because otherwise we are just going to have to reorg the tests then anyway, when some API things change.

**Comment by rdgao** [comment]
yep, sounds good

**Pull request merged**
