### PR TITLE
[WIP/ENH] - Add erp sim func

### PR DESCRIPTION
**Pull request by TomDonoghue**
Responds to #262 - adds a simulation function to create an ERP complex, simulated as a decaying (damped) sine wave. 

@ryanhammonds: could you take a quick look at this - do you think it's something worth adding? It's a very simple approach for adding ERPs, but seems worth adding something like this. If it looks good to you, the main potential update is to update it to vary the start time (I wasn't immediately clear on how to do this).

### CODE REVIEW

**Review by ryanhammonds — APPROVED** [review]
This is cool! This kind of reminds me of a damped oscillations, with an extra linear term.

I looked into how to have a start time, but the equation in the paper doesn't seem to work. I guess alternatives could be to np.roll the signal or to redefine the time array after simulating.

**Comment by TomDonoghue** [comment]
@ryanhammonds - yeh, it is pretty similar to a damped oscillator, basically, good point!

I also originally played around with manipulating the start time based on the original equation, and couldn't get it to work but I wasn't sure if I was just messing it up. Using np.roll or something like that seems like a good way to do it - do you want to try adding that?

Otherwise, the other possible thing to check in on is the name (as always...). I think `sim_erp` is obviously relevant, but thinking forward, I somewhat imagine we might add other ways to do this, and don't necessary want this is a the default version - in which case maybe we relabel it something a bit more specific?

**Comment by ryanhammonds** [comment]
@TomDonoghue I added a `time_start` arg that let's one specify where in the signal the erp should start, assuming samples prior to the start time should be zero. I did this over np.roll to avoid samples wrapping to the beginning of the signal in cases where slow decays are used.

I'm not too sure about a good func name. Maybe `sim_damped_erp`?

**Comment by TomDonoghue** [comment]
@ryanhammonds - awesome, thanks for adding the variable start time, that LGTM!

I've changed the name to `sim_damped_erp` - I think it's a good / descriptive label for this particular approach of creating ERPs. I've added that name to the API list, so this should be good to go, and I'm going to merge it in now!

**Pull request merged**
