### PR TITLE
[ENH] - Add IRASA

### PR DESCRIPTION
**Pull request by TomDonoghue**
Add an implementation of IRASA. 

Note - this implementation is inspired by / draws from the one in YASA:
https://github.com/raphaelvallat/yasa/blob/master/yasa/spectral.py#L326

Reviews / ToDos:
- @elybrand : if you feel like you have a sense of IRASA, can you check the implementation for technical sound-ness?
    -  also, I wanted to add the implementation so you can play with it. Feel free to 'explore' it for a while before proper reviewing
- @ryanhammonds : can you check the code elements & double check it is well organized to fit into NDSP
    - so far, there are no tests, so if you could add some code tests that would be great!
- @rdgao : tagging you in since you've played with IRASA a bit - but nothing in particular needed!
    - thought you might be interested in checking it out / sanity checking the implementation!

Some quickstart code to try it (it seems to work in the simple case):
```
from neurodsp.aperiodic.irasa import *

from neurodsp.sim import sim_combined
from neurodsp.spectral import compute_spectrum, trim_spectrum
from neurodsp.plts import plot_power_spectra

n_seconds, fs = 10, 1000
sim_components = {'sim_powerlaw': {'exponent' : -2},
                  'sim_oscillation': {'freq' : 10}}
sig = sim_combined(n_seconds=n_seconds, fs=fs, components=sim_components)
f1, p1 = trim_spectrum(*compute_spectrum(sig, fs), [1, 30])

freqs, psd_ap, psd_pe = irasa(sig, fs, noverlap=int(2*fs))
b0, b1 = fit_irasa(freqs, psd_ap)

print('Estimated intercept & slope: {:1.3f}, {:1.3f}'.format(b0, b1))
plot_power_spectra([f1, freqs], [p1, psd_ap], labels=['Original', 'IRASA-AP'])
```

Creates this output:
Screen Shot 2020-07-23 at 2 00 48 PM

### CODE REVIEW

**Comment by ryanhammonds** [comment]
@TomDonoghue Everything here looks good to me. I pushed tests updates.

**Comment by TomDonoghue** [comment]
Okay, this all looks sounds good to me!

@elybrand - thanks for the dive into the resampling! I was curious about the resampling approach here, and glad to see the different approaches seem equivalent! This is a a really nice sanity check to have. 
@ryanhammonds  - thanks for adding the tests! I mildly updated organization, if you want to sanity check that!

Some notes for myself:
This should be merged after #167. After that PR is merged, rebase here, and revisit for conflicts and check / update here for  test signals updates; aperiodic init file; API listing, then this can also be merged.

**Comment by ryanhammonds** [comment]
@TomDonoghue I went though your updates and everything looks good to me.

**Comment by TomDonoghue** [comment]
This all seems good then - merging in!

**Pull request merged**
