### PR TITLE
Add JOSS paper draft

### PR DESCRIPTION
**Pull request by TomDonoghue**
Adding a paper draft for a JOSS submission. 
JOSS: https://joss.theoj.org

Submission Guidelines: https://joss.readthedocs.io/en/latest/submitting.html

This PR is to edit / approve the JOSS paper draft, to prep for submission. 

Paper draft by @voytek - I just moved the files. 

To Do: @srcole, @rdgao & I: if we all want to read through this file and suggest edits / approve it, then once that's ready (and any other relevant updates go though), then the repo is ready to submit to JOSS.

### CODE REVIEW

**Comment by voytek** [comment]
One thing to note here is that we need some references. For JOSS, the "paper" itself is very short. It's all about the code.

[Here's](https://joss.readthedocs.io/en/latest/submitting.html) their example paper, for reference.

**Comment by rdgao** [comment]
good with me

**Comment by TomDonoghue** [comment]
Just read through it, made some updates:
- Since Scott isn't affiliated with CogSci, I changed the affiliation ordering so it doesn't start at 2.
- Updated the keywords a bit (remove DSP, since it's in the title, but added a couple others)
- Added references where were missing (Buzsaki refs for LFPs & oscillations, & He ref for 1/f)
- Re-ordered references to be in alphabetical order. Also removed irrelevant fields
- Added sections to the paper
- Slightly re-organized the summary, and added a note on how it relates to related tools such as MNE (I think we should acknowledge this)

I'm not totally convinced with how I wrote about how it fits into the broader ecosystem (it's relation to MNE, etc, how it's a lightweight tool that offers other stuff that can be plugged in) - so if people want to eyeball that part, that would be good. I think we should think a little about and write in a comment on this (scoping & how it relates to other things, mention other things like MNE, but point out we're not trying to compete with that). 

Other than that note, all looks good to me.

**Comment by voytek** [comment]
Okay, it's all ready to go.

**Comment by voytek** [comment]
Okay, last little grammar edits and now I'm done.

**Pull request merged**
